export const cjData = [
  {
    actionStatus: 'closed',
    actionType: 'item_sale',
    validationStatus: 'AUTOMATED',
    original: true,
    actionTrackerId: '372642',
    actionTrackerName: 'Nook and Digital Product Sales',
    advertiserName: 'Barnes & Noble',
    postingDate: '2020-07-14T13:30:19Z',
    pubCommissionAmountUsd: '10',
    shopperId: '1',
    saleAmountUsd: '0',
    correctionReason: null,
    orderDiscountUsd: '0',
    aid: '13261435',
    orderId: '4098759842',
    commissionId: '2672869066',
    saleAmountPubCurrency: '10',
    orderDiscountPubCurrency: '0',
    advertiserId: '4258829',
    items: [
      {
        quantity: 1,
      },
    ],
  },
  {
    actionStatus: 'closed',
    actionType: 'item_sale',
    validationStatus: 'AUTOMATED',
    original: false,
    actionTrackerId: '372642',
    actionTrackerName: 'Nook and Digital Product Sales',
    advertiserName: 'Barnes & Noble',
    postingDate: '2020-07-17T15:45:25Z',
    pubCommissionAmountUsd: '30',
    shopperId: '2',
    saleAmountUsd: '0',
    correctionReason: 'OTHER_REASON',
    orderDiscountUsd: '0',
    aid: '13261435',
    orderId: '4098759842',
    commissionId: '2674255473',
    saleAmountPubCurrency: '5',
    orderDiscountPubCurrency: '0',
    advertiserId: '4258829',
    items: [
      {
        quantity: -1,
      },
    ],
  },
  {
    actionStatus: 'new',
    actionType: 'item_sale',
    validationStatus: 'AUTOMATED',
    original: true,
    actionTrackerId: '372642',
    actionTrackerName: 'Nook and Digital Product Sales',
    advertiserName: 'Barnes & Noble',
    postingDate: '2020-07-27T11:00:26Z',
    pubCommissionAmountUsd: '60',
    shopperId: '1',
    saleAmountUsd: '0',
    correctionReason: null,
    orderDiscountUsd: '0',
    aid: '12366832',
    orderId: '4099363131',
    commissionId: '2678093328',
    saleAmountPubCurrency: '0',
    orderDiscountPubCurrency: '0',
    advertiserId: '4258829',
    items: [
      {
        quantity: 1,
      },
    ],
  },
  {
    actionStatus: 'closed',
    actionType: 'item_sale',
    validationStatus: 'AUTOMATED',
    original: true,
    actionTrackerId: '372642',
    actionTrackerName: 'Nook and Digital Product Sales',
    advertiserName: 'Barnes & Noble',
    postingDate: '2020-07-27T11:01:45Z',
    pubCommissionAmountUsd: '15',
    shopperId: '1',
    saleAmountUsd: '0.99',
    correctionReason: null,
    orderDiscountUsd: '0',
    aid: '12366832',
    orderId: '4099363133',
    commissionId: '2678096251',
    saleAmountPubCurrency: '0.99',
    orderDiscountPubCurrency: '0',
    advertiserId: '4258829',
    items: [
      {
        quantity: 1,
      },
    ],
  },
  {
    actionStatus: 'new',
    actionType: 'item_sale',
    validationStatus: 'AUTOMATED',
    original: true,
    actionTrackerId: '372642',
    actionTrackerName: 'Nook and Digital Product Sales',
    advertiserName: 'Barnes & Noble',
    postingDate: '2020-07-27T12:00:11Z',
    pubCommissionAmountUsd: '11',
    shopperId: null,
    saleAmountUsd: '0',
    correctionReason: null,
    orderDiscountUsd: '0',
    aid: '13261435',
    orderId: '4099360794',
    commissionId: '2678118763',
    saleAmountPubCurrency: '0',
    orderDiscountPubCurrency: '0',
    advertiserId: '4258829',
    items: [
      {
        quantity: 1,
      },
    ],
  },
  {
    actionStatus: 'new',
    actionType: 'item_sale',
    validationStatus: 'AUTOMATED',
    original: false,
    actionTrackerId: '372642',
    actionTrackerName: 'Nook and Digital Product Sales',
    advertiserName: 'Barnes & Noble',
    postingDate: '2020-07-31T14:10:30Z',
    pubCommissionAmountUsd: '30',
    shopperId: null,
    saleAmountUsd: '0',
    correctionReason: 'OTHER_REASON',
    orderDiscountUsd: '0',
    aid: '13261435',
    orderId: '4099360794',
    commissionId: '2679922998',
    saleAmountPubCurrency: '0',
    orderDiscountPubCurrency: '0',
    advertiserId: '4258829',
    items: [
      {
        quantity: -1,
      },
    ],
  },
  {
    actionStatus: 'new',
    actionType: 'item_sale',
    validationStatus: 'AUTOMATED',
    original: false,
    actionTrackerId: '372642',
    actionTrackerName: 'Nook and Digital Product Sales',
    advertiserName: 'Barnes & Noble',
    postingDate: '2020-07-31T14:12:01Z',
    pubCommissionAmountUsd: '0',
    shopperId: '1',
    saleAmountUsd: '1000',
    correctionReason: 'OTHER_REASON',
    orderDiscountUsd: '0',
    aid: '12366832',
    orderId: '4099363133',
    commissionId: '2679925168',
    saleAmountPubCurrency: '-0.99',
    orderDiscountPubCurrency: '0',
    advertiserId: '4258829',
    items: [
      {
        quantity: -1,
      },
    ],
  },
  {
    actionStatus: 'new',
    actionType: 'item_sale',
    validationStatus: 'AUTOMATED',
    original: false,
    actionTrackerId: '372642',
    actionTrackerName: 'Nook and Digital Product Sales',
    advertiserName: 'Barnes & Noble',
    postingDate: '2020-07-31T14:12:45Z',
    pubCommissionAmountUsd: '100',
    shopperId: '1',
    saleAmountUsd: '0',
    correctionReason: 'OTHER_REASON',
    orderDiscountUsd: '0',
    aid: '12366832',
    orderId: '4099363131',
    commissionId: '2679926170',
    saleAmountPubCurrency: '0',
    orderDiscountPubCurrency: '0',
    advertiserId: '4258829',
    items: [
      {
        quantity: -1,
      },
    ],
  },
];
